# Address on which the server listens
listen_if: 0.0.0.0
listen_port: 8951
#advertise_addr: 127.0.0.0:8951

extractor:
  name: "minilm-l6-v2-embeddings"
  path: "minilm_l6_embedding.MiniLML6Extractor"
  driver: "python"

  # name: "bert-entity-extractor"
  # path: "entity_extractor.EntityExtractor"
  # driver: "python"

# Database URL for storing document and memory
coordinator_addr: 192.168.1.14:8950

